# Generated by Django 5.2.13 on 2026-05-12 11:53

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui Pada')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Pelanggan')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=15, verbose_name='No. Telepon')),
                ('loyalty_points', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Poin Loyalitas')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Alamat')),
            ],
            options={
                'verbose_name': 'Pelanggan',
                'verbose_name_plural': 'Pelanggan',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui Pada')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Produk')),
                ('category', models.CharField(choices=[('food', 'Makanan'), ('beverage', 'Minuman'), ('snack', 'Snack'), ('merchandise', 'Merchandise'), ('other', 'Lainnya')], default='other', max_length=50, verbose_name='Kategori')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Harga (Rp)')),
                ('stock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stok')),
                ('is_available', models.BooleanField(default=True, verbose_name='Tersedia')),
            ],
            options={
                'verbose_name': 'Produk',
                'verbose_name_plural': 'Produk',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui Pada')),
                ('full_name', models.CharField(max_length=150, verbose_name='Nama Lengkap')),
                ('position', models.CharField(choices=[('manager', 'Manager'), ('cashier', 'Kasir'), ('barista', 'Barista'), ('waiter', 'Pelayan'), ('supervisor', 'Supervisor')], default='cashier', max_length=50, verbose_name='Jabatan')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Gaji (Rp)')),
                ('employee_status', models.CharField(choices=[('active', 'Aktif'), ('inactive', 'Tidak Aktif'), ('on_leave', 'Cuti')], default='active', max_length=20, verbose_name='Status Karyawan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL, verbose_name='Akun Login')),
            ],
            options={
                'verbose_name': 'Karyawan',
                'verbose_name_plural': 'Karyawan',
                'ordering': ['position', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui Pada')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total (Rp)')),
                ('status', models.CharField(choices=[('pending', 'Menunggu'), ('completed', 'Selesai'), ('cancelled', 'Dibatalkan')], default='completed', max_length=20, verbose_name='Status')),
                ('payment_method', models.CharField(choices=[('cash', 'Tunai'), ('debit', 'Kartu Debit'), ('transfer', 'Transfer Bank'), ('qris', 'QRIS')], default='cash', max_length=20, verbose_name='Metode Pembayaran')),
                ('cashier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='Kasir')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='pos.customer', verbose_name='Pelanggan')),
            ],
            options={
                'verbose_name': 'Transaksi',
                'verbose_name_plural': 'Transaksi',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Jumlah')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Harga Satuan')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Subtotal')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_items', to='pos.product', verbose_name='Produk')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pos.transaction', verbose_name='Transaksi')),
            ],
            options={
                'verbose_name': 'Item Transaksi',
                'verbose_name_plural': 'Item Transaksi',
            },
        ),
    ]
